### ISSUE TITLE
Reverse disassembly documentation

### ISSUE THREAD

**Issue by ijacquez** [romhack/Mgs-Gb-translation#2]
I've been reverse engineering the game for a while.

I can provide a file with my notes if you like.

I'm particularly searching for where the game level data is stored.

**Comment by romhack** [comment]
Hello, Israel.
This is outdated repository - current translation discussion is ongoing at bitbucket repo, as most of my team don't have github accounts. I will either mirror here from bitbucket or delete it.
Thank you for proposal, but my translation project is already complete and now in testing phase, probably I will need no additional information.
I've been reverse engineering this game since 2016 and have a vast IDA database with commented code mostly for text part of game engine. 
You can always contact me [by email ](https://romhack.github.io/about.html) and I'll help you if I can.
